version: "3"

services:
  remark:
    image: umputun/remark42:latest
    container_name: "remark42"
    hostname: "remark42"
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      - REMARK_URL=https://remark42.vs.computer
      - DEBUG=true
      - SITE_ID=remark
      - AUTH_ANON=true
      - EMOJI=true
      - SECRET=/run/secrets/secret
      - AUTH_GITHUB_CID=7a9e6043085adde1be83
      - AUTH_GITHUB_CSEC=/run/secrets/auth_github_csec
    volumes:
      - reviews:/srv/var
  nginx:
    build: ./hugo/
    container_name: "nginx"
    hostname: "nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/me.vs.computer/fullchain.pem:/etc/letsencrypt/live/me.vs.computer/fullchain.pem:ro
      - /etc/letsencrypt/live/me.vs.computer/privkey.pem:/etc/letsencrypt/live/me.vs.computer/privkey.pem:ro
      - /etc/letsencrypt/live/remark42.vs.computer/fullchain.pem:/etc/letsencrypt/live/remark42.vs.computer/fullchain.pem:ro
      - /etc/letsencrypt/live/remark42.vs.computer/privkey.pem:/etc/letsencrypt/live/remark42.vs.computer/privkey.pem:ro
    depends_on:
      remark:
        condition: service_healthy

secrets:
  auth_github_csec:
    file: ./.secrets/github_client_secret.txt
  secret:
    file: ./.secrets/secret.txt

volumes:
  reviews:
