version: "3"

services:
  remark:
    image: umputun/remark42:latest
    container_name: "remark42"
    hostname: "remark42"
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      - REMARK_URL=http://remark42:8080
      - SECRET=super-secret-code
      - DEBUG=true
      - SITE_ID=remark
      - AUTH_ANON=true
      # - AUTH_GOOGLE_CID
      # - AUTH_GOOGLE_CSEC
      # - AUTH_GITHUB_CID
      # - AUTH_GITHUB_CSEC
      # Enable it only for the initial comment import or for manual backups.
      # Do not leave the server running with the ADMIN_PASSWD set if you don't have an intention
      # to keep creating backups manually!
      # - ADMIN_PASSWD=<your secret password>
    volumes:
      - reviews:/srv/var
  nginx:
    build: ./hugo/
    container_name: "nginx"
    hostname: "nginx"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      remark:
        condition: service_started
      certbot:
        condition: service_completed_successfully
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email camachom@fastmail.com -d me.vs.computer -d remark42.vs.computer --agree-tos --non-interactive

volumes:
  reviews:
