version: "2"

services:
  hugo:
    image: klakegg/hugo:0.101.0-alpine
    container_name: "hugo"
    hostname: "hugo"
    volumes:
      - ./hugo:/src:rw
      - static-content:/target
  remark:
    image: umputun/remark42:latest
    container_name: "remark42"
    hostname: "remark42"
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      - REMARK_URL=http://remark42:8080
      - SECRET="super secret"
      - DEBUG=true
      - SITE=localhost
      - AUTH_ANON=true
      # - AUTH_GOOGLE_CID
      # - AUTH_GOOGLE_CSEC
      # - AUTH_GITHUB_CID
      # - AUTH_GITHUB_CSEC
      # Enable it only for the initial comment import or for manual backups.
      # Do not leave the server running with the ADMIN_PASSWD set if you don't have an intention
      # to keep creating backups manually!
      # - ADMIN_PASSWD=<your secret password>
    volumes:
      - reviews:/srv/var
    depends_on:
      - hugo
  nginx:
    image: nginx:alpine
    container_name: "nginx"
    hostname: "nginx"
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static-content:/usr/share/nginx/html/
    depends_on:
      - hugo
      - remark
volumes:
  static-content:
  reviews:
